### ISSUE TITLE
Add Jokes to HACS default integrations

### ISSUE THREAD

**Issue by LaggAt** [LaggAt/ha-jokes#1]
HowTo:
* fork hacs/defaults
* create branch: integration-jokes
* create pull request in hacs/default:master
* check for successful completion of all checks in PR
* wait for someone to review/merge

**Comment by LaggAt** [comment]
PR: https://github.com/hacs/default/pull/1577

**Comment by mvdwetering** [comment]
It is added as that is how I found it :)
