### ISSUE TITLE
How do I use this? 

### ISSUE THREAD

**Issue by jamiekris** [LaggAt/ha-jokes#10]
Hi, sorry I'm a bit of a beginner here, but could you please provide some examples of how to use this? Perhaps as a card?

**Comment by brianewman** [comment]
Here's how I use it:

```
type: markdown
content: |
  {{ states('sensor.random_joke') }}
```

Or from the GUI, just create a Markdown card and put `{{ states('sensor.random_joke') }}` in the content field.

**Comment by jamiekris** [comment]
Thanks! I've installed this via HASS, however I do not see any sensor called random_joke. What might I be missing here?

**Comment by seanmccabe** [comment]
> Thanks! I've installed this via HASS, however I do not see any sensor called random_joke. What might I be missing here?

You need to go to the devices and services page in settings, and install from there once downloaded from HACS

**Comment by jamiekris** [comment]
Thanks! That worked.

**Comment by evanthomas** [comment]
Another newbie here. This doesn't work for me. `{{ states('sensor.random_joke') }}` just produces `unknown`. On the other hancd, `{{ states('update.jokes_update') }}`, which matches the entity id, produces `off`.
