### ISSUE TITLE
Better sensor icon would be nice

### ISSUE THREAD

**Issue by mvdwetering** [LaggAt/ha-jokes#3]
Hi, not sure how much you are planning to update this integration as it is marked as an example, but it would be nice if the default icon for the sensor would be a bit more random or "joke-y". The default eye looks a bit weird.

![image](https://user-images.githubusercontent.com/732514/208527552-dd389bdf-b112-49cb-82c4-ae620b0b1e38.png)

When looking on MDI for icons the ones shown when searching for "emoj" are probably most suitable.

It would even be better if it would be possible to change the icon yourself as a user, but that currently does not work as the sensor does not have a uniqueid.

![image](https://user-images.githubusercontent.com/732514/208527884-d3ce2084-0f88-4767-9131-d860e9942834.png)

EDIT: I am dumb; I can actually override it easily in the new Tile card instead of the entity settings. But still a nicer default would be cool.

**Comment by LaggAt** [comment]
If you want you can start an PR for this. Thanks.
