### ISSUE TITLE
suggestion for card to use please

### ISSUE THREAD

**Issue by raoulteeuwen** [LaggAt/ha-jokes#4]
Thank you for this integration :-). What is the best card for it? I'm using the entity card, but it shows the first couple of characters of the joke in a rather big font and I need to click it to read the whole joke; is there a way to see the whole joke text without needing to click :-)?

**Comment by mvdwetering** [comment]
I tried the [multiline entity card](https://github.com/jampez77/Multiline-Entity-Card) which looks like below, but the font is kind of big.
![image](https://user-images.githubusercontent.com/732514/208989546-b4bdbdc5-fec1-49e4-828a-2d2e5dab7523.png)

I also tried the standard Home Assistant Tile card which I like a lot better, but it only works for short jokes.
I tried to change the `textoverflow` with `card-mod` so it would not use the ellipses anymore, but did not get that working yet.
![image](https://user-images.githubusercontent.com/732514/208989883-fd4a1e1d-2cfb-4b39-916d-d2c150783aa4.png)

Open to more suggestions

**Comment by n00bcodr** [comment]
Mushroom Title Card (the first one) and Mushroom Template Card (the second one) from [Lovelace Mushroom Cards](https://github.com/piitaya/lovelace-mushroom). Both of them look good to me.

![image](https://user-images.githubusercontent.com/49611451/209131049-81f06995-dac9-49b4-bed8-093318ea4746.png)

**Comment by LaggAt** [comment]
As this is just a minimalistic integration to develop/test my devcontainer, I'll not add anything right now.
Feel free to do a Pull Request, I'll check and accept minimalistic changes.
