### ISSUE TITLE
Cannot find sensor.

### ISSUE THREAD

**Issue by n00bcodr** [LaggAt/ha-jokes#5]
Installed through HACS.
The sensor is not showing up.

![image](https://user-images.githubusercontent.com/49611451/209121327-422ab37e-f09f-4d2e-8e81-c8d038bbc7af.png)

Edit : My bad. You have to add the integration after downloading the component in HACS

**Comment by Wetzel402** [comment]
I had this issue too until I found this closed issue.  It would be good to add some basic setup instructions to the readme.
